поправила
MardeevaSvetlana/autotests_course pull request #13
Opened 2023-05-22 13:09 UTC by MardeevaSvetlana

еще раз спасибо

2023-05-29 04:45 UTC, xmb1pb requested changes

2023-05-29 04:45 UTC, xmb1pb commented on homework8/task1.py
> +            raise TypeError
по заданию если в кортеже много данных, то надо просто райзить общий Exception не обрабатывая его, а у тебя TypeError
сделай это отдельной проверкой и кидай его сразу, дальше код все равно не будет выполняться

2023-05-29 04:45 UTC, xmb1pb commented on homework8/task1.py
> +            return 'Недостаточно данных'
конструкция в целом неверная. ты кидаешь TypeError и в его обработчике пытаешься ветвить поведение. Зачем обрабатывать в TypeError кейс с недостатком данных, если тебе кортеж с одинм элементом при попытке обращения к несуществующему второму элементу сам кинет IndexError?
хватай его except IndexError и возвращай нужное сообщение

2023-05-29 04:45 UTC, xmb1pb commented on homework8/task1.py
> +            return 'Много данных'
про много данных выше написал

2023-05-29 04:45 UTC, xmb1pb commented on homework8/task1.py
> +
сама структура функции должна быть примерно такой:
в блоке try пытаемся сложить два элемента и ловим исключения. 
в блоке except
если TypeError то возвращаем одно сообщение
если IndexError то возвращаем другое сообщение
если длина кортежа больше чем надо просто кидаем Exception
вне блока try-except если мы до него дошли то просто возвращаем результат сложения

2023-05-29 04:45 UTC, xmb1pb commented on homework8/task2.py
> +        except TypeError:
в этом задании надо только кидать исключения, а не перехватывать их тут же. 
просто пиши raise TypeError('сообщение')
ну или какой там надо Erorr по ситуации

ну и try тоже убери

просто if (что-то):
      raise ЧтотоError

2023-05-30 09:39 UTC, MardeevaSvetlana commented
готово

2023-05-31 01:40 UTC, merged

2023-05-31 01:40 UTC, MardeevaSvetlana commented
готово